// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindLens.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MindLens.Api.Data.Migrations.Tenant
{
    [DbContext(typeof(TenantContext))]
    [Migration("20260630105929_InitialTenant")]
    partial class InitialTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MindLens.Api.Models.Journaling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiReplyKey")
                        .HasColumnType("text");

                    b.Property<string>("AiReplyText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Text");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Transcription")
                        .HasColumnType("text");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("VoiceRecordKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId");

                    b.ToTable("Journalings");
                });

            modelBuilder.Entity("MindLens.Api.Models.JournalingAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Text");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<Guid>("JournalingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Transcription")
                        .HasColumnType("text");

                    b.Property<string>("VoiceRecordUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JournalingId");

                    b.HasIndex("QuestionId");

                    b.ToTable("JournalingAnswers");
                });

            modelBuilder.Entity("MindLens.Api.Models.JournalingRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalyzedContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<Guid>("JournalingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pillar_type");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("JournalingId");

                    b.ToTable("JournalingRegisters");
                });

            modelBuilder.Entity("MindLens.Api.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("MindLens.Api.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgeRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GlobalUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasPreviousTherapy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LivingSituation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryGoal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelationshipStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MindLens.Api.Models.PresessionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FlashBriefing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId")
                        .IsUnique();

                    b.ToTable("PresessionReports");
                });

            modelBuilder.Entity("MindLens.Api.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pillar_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("MindLens.Api.Models.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("FinishedAt")
                        .HasColumnType("date");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionDay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("InProcess");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("MindLens.Api.Models.TreatmentQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("TreatmentQuestions");
                });

            modelBuilder.Entity("MindLens.Api.Models.WeeklyClusterReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Vector>("ClusterEmbedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pillar_type");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClusterEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ClusterEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ClusterEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("WeeklyReportId");

                    b.ToTable("WeeklyClusterReports");
                });

            modelBuilder.Entity("MindLens.Api.Models.WeeklyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("FinishedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId");

                    b.ToTable("WeeklyReports");
                });

            modelBuilder.Entity("MindLens.Api.Models.Journaling", b =>
                {
                    b.HasOne("MindLens.Api.Models.Treatment", "Treatment")
                        .WithMany("Journalings")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("MindLens.Api.Models.JournalingAnswer", b =>
                {
                    b.HasOne("MindLens.Api.Models.Journaling", "Journaling")
                        .WithMany("JournalingAnswers")
                        .HasForeignKey("JournalingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindLens.Api.Models.Question", "Question")
                        .WithMany("JournalingAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Journaling");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MindLens.Api.Models.JournalingRegister", b =>
                {
                    b.HasOne("MindLens.Api.Models.Journaling", "Journaling")
                        .WithMany("JournalingRegisters")
                        .HasForeignKey("JournalingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Journaling");
                });

            modelBuilder.Entity("MindLens.Api.Models.Note", b =>
                {
                    b.HasOne("MindLens.Api.Models.Treatment", "Treatment")
                        .WithMany("Notes")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("MindLens.Api.Models.PresessionReport", b =>
                {
                    b.HasOne("MindLens.Api.Models.Treatment", "Treatment")
                        .WithOne("PresessionReport")
                        .HasForeignKey("MindLens.Api.Models.PresessionReport", "TreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("MindLens.Api.Models.Treatment", b =>
                {
                    b.HasOne("MindLens.Api.Models.Patient", "Patient")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MindLens.Api.Models.TreatmentQuestion", b =>
                {
                    b.HasOne("MindLens.Api.Models.Question", "Question")
                        .WithMany("TreatmentQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindLens.Api.Models.Treatment", "Treatment")
                        .WithMany("TreatmentQuestions")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("MindLens.Api.Models.WeeklyClusterReport", b =>
                {
                    b.HasOne("MindLens.Api.Models.WeeklyReport", "WeeklyReport")
                        .WithMany("WeeklyClusterReports")
                        .HasForeignKey("WeeklyReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("MindLens.Api.Models.WeeklyReport", b =>
                {
                    b.HasOne("MindLens.Api.Models.Treatment", "Treatment")
                        .WithMany("WeeklyReports")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("MindLens.Api.Models.Journaling", b =>
                {
                    b.Navigation("JournalingAnswers");

                    b.Navigation("JournalingRegisters");
                });

            modelBuilder.Entity("MindLens.Api.Models.Patient", b =>
                {
                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("MindLens.Api.Models.Question", b =>
                {
                    b.Navigation("JournalingAnswers");

                    b.Navigation("TreatmentQuestions");
                });

            modelBuilder.Entity("MindLens.Api.Models.Treatment", b =>
                {
                    b.Navigation("Journalings");

                    b.Navigation("Notes");

                    b.Navigation("PresessionReport")
                        .IsRequired();

                    b.Navigation("TreatmentQuestions");

                    b.Navigation("WeeklyReports");
                });

            modelBuilder.Entity("MindLens.Api.Models.WeeklyReport", b =>
                {
                    b.Navigation("WeeklyClusterReports");
                });
#pragma warning restore 612, 618
        }
    }
}
