worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    server {
        listen 80;

        # Opcional: Servir un mensaje de salud en la raíz
        location / {
            return 200 'Journal API Gateway funcionando correctamente.';
            add_header Content-Type text/plain;
        }

        # Todas las llamadas que empiecen con /api/ van al backend de C#
        location /api/ {
            proxy_pass http://backend:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_addrs;
        }
    }
}
