FROM python:3.11-slim
WORKDIR /app

# Instalar dependencias del sistema necesarias para compilar psycopg2 y ffmpeg para audio
RUN apt-get update && apt-get install -y libpq-dev gcc ffmpeg && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "-u", "main.py"]
